version: '3.8'
services:
  exiftool:
    #entrypoint: ["/bin/sh", "./exiftool.sh"]
    container_name: 'exiftool'
    build:
      context: .
      dockerfile: dockerfile
    image: ai2ys/exiftool:0.0.0
    stdin_open: true # equivalent: docker run -i 
    #tty: true
