version: '3.8'
services:
  exiftool:
    container_name: 'exiftool'
    build:
      context: .
      dockerfile: dockerfile
    image: ai2ys/exiftool:0.0.0
    # tty: false
    # stdin_open: true # equivalent: docker run -i 
